### ISSUE TITLE
redirect loop on Brave

### ISSUE THREAD

**Issue by ruanmartinelli** [siddharthkp/notes#2]
Hi, first of all congratulations on the app!

When opening it on my phone and after sign in with my twitter account I get stuck in a redirect loop between twitter and notella.

The redirect cycle goes like: _notella.now.sh_ --> _firebase url_ --> _twitter auth page_ --> _back to notella_

This seems to be an issue with Brave for Android as I wasn't able to reproduce the behavior on Chrome.

**Comment by siddharthkp** [comment]
Ouch! Any ideas on how to fix it?

**Comment by billiegoose** [comment]
Saw notella on zeithq's Twitter. Is twitter required to use a note taking app? The site redirects me right back to the OAuth page if I decline to grant it access. I'm thinking this might be the underlying cause of the redirect loop. Maybe add a manual Twitter Login button instead of trying to login automatically?

**Comment by siddharthkp** [comment]
@wmhilton that's interesting. any ideas on how to solve that?

**Comment by billiegoose** [comment]
Well... it looks like [here](https://firebase.google.com/docs/auth/web/twitter-login) you say "if there is no `user`, login with redirect" but that runs on page load. So you'll just keep redirecting to Twitter every time a use clicks "Cancel".

Instead of listening to `firebase.auth().onAuthStateChanged` I would use the login methods describe [here](https://firebase.google.com/docs/auth/web/twitter-login) and preferably only prompt the user to login when they try to save their notes. That way users can try it before signing in. It looks like Firebase has some other authentication options besides just Twitter too, for people who don't have Twitter.
